# Generated by Django 5.2.10 on 2026-02-06 09:48

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["last_name", "last_name_optional", "first_name"],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.AlterField(
            model_name="patient",
            name="doctor_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="doctor allocated by quota",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="relatives",
            field=models.ManyToManyField(blank=True, to="medical.patient"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="connections",
            field=models.ManyToManyField(blank=True, to="medical.problem"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="attending physician",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="staff_type",
            field=models.CharField(
                choices=[("A", "Administrative"), ("D", "Doctor")],
                default="A",
                max_length=1,
                verbose_name="staff type",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="document",
            field=models.FileField(
                upload_to="medical_tests/%Y/%m/%d", verbose_name="document"
            ),
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(fields=["patient"], name="history_patient_59cccd_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["last_name", "first_name"], name="patient_last_na_abf268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["birth_date"], name="patient_birth_d_0c20e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["tin"], name="patient_tin_6e8550_idx"),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["patient", "order_number"], name="problem_patient_da215c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["closing_date", "modified"], name="problem_closing_0d1a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["problem"], name="medical_tes_problem_620312_idx"
            ),
        ),
    ]
